### ISSUE TITLE
Vista home. Muro de ofertas

### ISSUE THREAD

**Issue by aronmero** [aronmero/proyecto-final-daw#26]
**Separación y Destaque de Reseñas y Calificaciones**

- [x] Las reseñas y calificaciones de usuarios dentro de la aplicación se destacarán en el muro, brindando visibilidad a las experiencias locales auténticas y relevantes.

**Interacción Intuitiva con Ofertas**

- [x] La interfaz de usuario permitirá a los usuarios interactuar fácilmente con las ofertas, ya sea para guardarlas, compartirlas o acceder directamente a los comercios locales asociados.

**Promociones Destacadas de Eventos Comunitarios**

- [x] Además de ofertas de comercios, el muro destacará promociones especiales y eventos comunitarios, ofreciendo una variedad de oportunidades para los usuarios.

**Comment by RevanHUB** [comment]
Se ha incluído en figma el diseño de los comentarios, he añadido componente en cada uno, que puede ser reutilizado si se quiere utilizar en los perfiles de cada uno de los usuarios (pero como no hay tiempo, imagino que no).

Falta por implementar el modal de los comentarios en el código de esta vista.
